apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-nodpsf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-nodpsf
    app.kubernetes.io/part-of: build-suite-test-application-oaqa
  name: test-annotations-nodpsf
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-annotations-nodpsf
status:
  loadBalancer: {}
