apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-annotations-nodpsf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-frbm-tenant/build-suite-test-application-oaqa/test-annotations-nodpsf@sha256:18007003eedc7ea012abdfb529b7809247e224bae3485a3529dcfacd19351a8d
        name: my-go
        resources: {}
status: {}
