apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-nodpsf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-nodpsf
    app.kubernetes.io/part-of: build-suite-test-application-oaqa
  name: test-annotations-nodpsfblbs
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: test-annotations-nodpsf
    weight: null
status: {}
